name: Node CI

# oliver-calculator-CAC
# oliver-calculator-EAS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [8.x, 10.x, 12.x]
        node-version: [10.x]

    steps:
    - name: 'Checkout Github Action'
    # - uses: actions/checkout@v1
      uses: actions/checkout@master

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # comment-out caching for this deployment perf test
    # - name: Cache node modules
    #   uses: actions/cache@v1
    #   with:
    #     path: node_modules
    #     key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

    # - name: Synopsys Detect
    #   uses: blackducksoftware/github-action@2.0.0
    #   with:
    #   # --detect.report.timeout is in seconds.
    #     args: '--detect.report.timeout=600 --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'

    - name: npm install, build, test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
      # env:
      #   CI: true

  deploy-CAC:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Azure webapp deploy -> CAC'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: oliver-calculator-CAC
        publish-profile: ${{ secrets.AZURE_CRED_CAC }}

  deploy-EAS:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Azure webapp deploy -> EAS'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: oliver-calculator-EAS
        publish-profile: ${{ secrets.AZURE_CRED_EAS }}