name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

    - name: Synopsys Detect
      uses: blackducksoftware/github-action@2.0.0
      with:
      # --detect.report.timeout is in seconds.
        args: '--detect.report.timeout=600 --blackduck.url="${{ secrets.BLACKDUCK_URL}}" --blackduck.api.token="${{ secrets.BLACKDUCK_API_TOKEN}}" --detect.risk.report.pdf=true'

    - name: npm install
      run: |
        npm install
      env:
        CI: true

    - name: build
      run: |
        npm run build --if-present
      env:
        CI: true

    - name: test
      run: |
        npm test
      env:
        CI: true
